services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - PORT=${APP_PORT}
    volumes:
      - ./src:/app/src
  mysql_db:
    image: mysql
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_TCP_PORT=${DB_PORT}
