services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '${APP_PORT}:${APP_PORT}'
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
  mysql_db_prod:
    image: mysql
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_TCP_PORT=${DB_PORT}
